library(readxl)
library(bkmr)
library(ggplot2)
data<-read_excel("C:\\Users\\Hp\\Desktop\\EM.xlsx")
Step2:
# Extract outcome, exposures, and covariates
y <- data$Preeclampsia
Z <- as.matrix(data[, c("Copper","Selenium","Molybednum","Manganese","Cobalt")]) 
X <- matrix(1, nrow = nrow(data), ncol = 1)  # Intercept only
Step3:
 # Remove rows with NA (if any remain)
 complete_cases <- complete.cases(Z, y, X)
Z <- Z[complete_cases, ]
 y <- y[complete_cases]
 X <- X[complete_cases, ]
Z <- scale(Z)
Step4:
set.seed(123)
 fit_bkmr <- kmbayes(y = y, Z = Z, X = X, family = "binomial", 
                    iter = 5000, verbose = FALSE, varsel=TRUE)
Step5:
univar_response <- PredictorResponseUnivar(fit = fit_bkmr, ngrid = 50)
Step6:
p_total <- ggplot(univar_response, aes(x = z, y = est, ymin = est - 1.96 * se, ymax = est + 1.96 * se)) +
  geom_smooth(stat = "identity", color = "blue", fill = "grey70") +
  facet_wrap(~variable, scales = "free_x", ncol = 5, strip.position = "top") +
  labs(title = "Total population", x = "expos", y = "h(expos)")
print(p_total)
